include NickelHook/NickelHook.mk

override LIBRARY  := libpocketproxy.so
override SOURCES  += src/pocketproxy.cc 
override CFLAGS   += -Wall -Wextra -Werror
override CXXFLAGS += -Wall -Wextra -Werror -Wno-missing-field-initializers

include NickelHook/NickelHook.mk
