include NickelHook/NickelHook.mk

override LIBRARY  := libpocketproxy.so
override SOURCES  += src/pocketproxy.cc inih/ini.c
override CFLAGS   += -Wall -Wextra -Werror
override CXXFLAGS += -Wall -Wextra -Werror -Wno-missing-field-initializers
override KOBOROOT += adds/pocket_proxy:/mnt/onboard/.adds/pocket_proxy

include NickelHook/NickelHook.mk
