FROM golang:1.24-alpine AS build-stage

WORKDIR /src

COPY ./ ./
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/proxyserver main.go

FROM scratch

WORKDIR /proxyserver

COPY --from=build-stage /bin/proxyserver /proxyserver/proxyserver
COPY --from=build-stage /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 9090

ENTRYPOINT ["/proxyserver/proxyserver"]